name: DUxDRx
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19387
title: ' '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#040404'
    - '#242424'
    - '#bfbfbf'
    - '#0f0f0f'
  brandStrength: 1
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
