name: DUxDRx
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19387
title: 'DUxDRx -- #remediate'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cccccc'
    - '#f1f1f1'
    - '#000000'
    - '#e4e4e4'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
