name: DUxDRx
favicon: null
layout_spectrum: 0.8437429268378764
typography_spectrum: 0.8067521478515118
title: 'DUxDRx -- #remediate'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9311662304680794
  lightness: 0.1717211923096329
  saturation: 0.8644436963368207
  rhythmicContrast: 0.976775363786146
purpose: []
